### ISSUE TITLE
Add more robust handling for Date and Timestamp types

### ISSUE THREAD

**Issue by agasheesh** [cloudspannerecosystem/harbourbridge#219] opened 2021-11-09 23:38 UTC
Currently HarbourBridge assumes Date and Timestamp to follow ISO 8601 format and the data migration would fail if that is not the case. We should improve our handling of these types such that either customers can provide `--dateFormat` and `--timestampFormat` as flags or HarbourBridge could add support for detecting and using a few common formats.

A side note for PostgreSQL dialect Spanner databases as target: PG Spanner doesn't support Date as of this writing and we simply treat any input date as a string and store it as a string in Spanner. This can lead to dates such as "2021-42-1009" being written verbatim. One potential improvement would be to try and parse dates using the expanded list of valid formats and then convert to String if valid. Else, return an error.

**Comment by manitgupta** [comment] 2023-02-01 04:55
Duplicate of #355.

**Closed by manitgupta** 2023-02-01 04:55 UTC
