### ISSUE TITLE
Generate a more ingestable report 

### ISSUE THREAD

**Issue by Deep1998** [cloudspannerecosystem/harbourbridge#293] opened 2022-05-11 13:14 UTC
CEs want to present the HarbourBridge findings from the report to customers. They use the report to generate graphs and visualisations while presenting to customers which is currently difficult to collate since the report is outputted in a text format. 

We should also create a more query-able report (maybe CSV) that can be easily ingested into data visualisation tools to answer queries such as how many tables have auto increment? Row counts for each table? How many columns have default values? etc

This would include generating csvs for the tabular data in the reports, row count stats for tables, as well as tablewise stats for warnings listed [here](https://github.com/cloudspannerecosystem/harbourbridge/blob/master/internal/report.go#L264)

**Comment by Deep1998** [comment] 2022-05-26 10:03
We should aim to output these tables in the summary section.
1) Count stats per table
2) Schema conversion health counts
3) for dump mode, parsing status counts. Basically the following in a csv
```
  schema   data   skip  error  statement
  --------------------------------------
     113      0      0      0  CreateTableStmt
```
4) For each table, how many columns have each type of warning
```
 tbl_name|autoincrement|widened_storage|multidim_array|...
 abc|1|3|0
 xyz|0|0|0
```
5) Data conversion stats

**Comment by manitgupta** [comment] 2023-01-18 06:00
Duplicate of existing issue.

**Closed by manitgupta** 2023-01-18 06:00 UTC
Labels: good first issue
